volumes:
  data_sendy:
    labels:
      co.sendy.description: "Data volume for Sendy Database."

services:
  mariadb:
    image: mariadb
    volumes:
      - "data_sendy:/var/lib/mysql"
    environment:
      - "MARIADB_ROOT_PASSWORD=${SERVICE_PASSWORD_ROOT}"
      - "MARIADB_DATABASE=${MARIADB_DATABASE}"
      - "MARIADB_USER=${SERVICE_USER_MARIADB}"
      - "MARIADB_PASSWORD=${SERVICE_PASSWORD_MARIADB}"
    healthcheck:
      test:
        - CMD
        - healthcheck.sh
        - "--connect"
        - "--innodb_initialized"
      start_period: 10s
      interval: 5s
      timeout: 10s
      retries: 15

  sendy:
    hostname: sendy
    container_name: sendy
    depends_on:
      - mariadb
    image: sendy:latest
    build:
      context: .
      # target: debug   # Uncomment to enable XDEBUG build
    environment:
      SENDY_PROTOCOL: ${SENDY_PROTOCOL}
      SENDY_FQDN: ${SENDY_FQDN}
      MYSQL_HOST: mariadb
      MYSQL_DATABASE: ${MARIADB_DATABASE}
      MYSQL_USER: ${SERVICE_USER_MARIADB}
      MYSQL_PASSWORD: ${SERVICE_PASSWORD_MARIADB}
    ports:
      - "8080:80"
